### ISSUE TITLE
Pull requests automation service POC

### ISSUE THREAD

**Issue by Clivern** [Clivern/learning-istio#5]

**Comment by v0xk** [comment]
`.meerkat.yml` or `.meerkat.yaml`

```yaml
tasks:
  -
    title: Automatic Merge
    type: automatic_pr_merge

    conditions:
      -
        type: branching
        base_branch: master
      -
        type: labeling
        has_labels: merge,!work-in-progress
      -
        type: reviews
        approvals: 2
        reviewers: @clivern
      -
        type: checks
        passed: TravisCI

    actions:
        -
          type: merge_pr

  - 
    title: Auto Assign Labels
    type: auto_assign_labels

    labels:
      -
        name: bug
      - 
        name: feature
      - 
        name: question

  - 
    title: Welcome message to contribution
    type: welcome_message_to_contribution
    
```
Meerkat compare the PR against conditions on each PR change
